INSERT INTO `tintoreriaCI`.`tipo_documento` (`codigosiitdo`, `nombre___tdo` ) VALUES 
('29', 'Factura de Inicio'),
('30', 'Factura'),
('32', 'Factura de ventas y servicios no afectos o exentos'),
('33', 'Factura Electrónica'),
('34', 'Factura no Afecta o Exenta Electrónica'),
('35', 'Boletas de Ventas y Servicios'),
('38', 'Boletas No Afectas o Exentas'),
('39', 'Boletas Electrónica'),
('40', 'Liquidación factura'),
('41', 'Boletas No Afectas o Exentas Electrónica'),
('43', 'Liquidación-Factura Electrónica'),
('45', 'Factura de Compra'),
('46', 'Factura de Compra electrónica'),
('55', 'Nota de Débito'),
('56', 'Nota de Débito Electrónica'),
('60', 'Nota de Crédito'),
('61', 'Nota de Crédito Electrónica'),
('101', 'Factura de exportación'),
('102', 'Factura de venta exenta a zona franca primaria (Res. Ex. N° 601 de 07.05.82)'),
('103', 'Liquidación '),
('104', 'Nota de Débito de Exportación'),
('106', 'Nota de Crédito de Exportación'),
('105', 'Boletas liquidación (Res. Ex. N° 1423 del 23.12.76)'),
('108', 'SRF Solicitud Registro de Factura'),
('109', 'Factura a turista (Res. Ex. N° 6428 de 06.12.93)'),
('110', 'Factura de Exportación Electrónica'),
('111', 'Nota de Débito de Exportación Electrónica'),
('112', 'Nota de Crédito de Exportación Electrónica'),
('901', 'Factura de ventas a empresas del territorio preferencial (Res. Ex. N°1057 del 25.04.85)'),
('902', 'Conocimiento de Embarque (Marítimo o aéreo)'),
('903', 'Documento Único de Salida (DUS)'),
('904', 'Factura de Traspaso (Usuario Zona Franca)'),
('919', 'Resumen Ventas de nacionales pasajes sin Factura'),
('920', 'Otros registros no documentados. Aumenta débito'),
('922', 'Otros registros. Disminuye débito'),
('924', 'Resumen ventas de internacionales pasajes sin Factura ');